### PR TITLE
WIP: Bump servant to 0.14.*

### PR DESCRIPTION
**Pull request by xplat**
Unfortunately this involved rewriting a lot of things in .Internal
...

### CODE REVIEW

**Comment by imalsogreg** [comment]
Thanks! I wish I had seen this before I started working on 0.15/0.16. It looks like you fixed some other things (hoist w/ context, order of request checks). I need to rebase my work onto this.

I've been working on fixing the CI, and if I manage that, I'll rebase the change into something you can cherry-pick onto your branch, if you don't mind. Or, if you've run the test suite locally and it works, I'll just merge and do a release.

**Comment by imalsogreg** [comment]
@xplat Could you raise the lower bound on hspec-snap to 1.0.1.0? We just released that to hackage with changes that support more ghc's and more version of `hspec`. After that, your servant-0.14 PR is ready to merge.

**Comment by xplat** [comment]
Sorry for being nonresponsive.  Needed this at work for a project that involved a lot of other work too and I kind of moved along to that.  I'm glad you were still able to make use of it.

**Comment by imalsogreg** [comment]
No worries, thanks for the contribution :)

**Pull request merged**
